[build]
  publish = "dist"
  command = "npm run build"
[build.processing.html]
  pretty_urls = false
[[headers]]
  for = "/_astro/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[plugins]]
  package = "netlify-plugin-minify-html"
  # Specify which deploy contexts we'll minify HTML in.
  # Supports any Deploy Contexts available in Netlify.
  # https://docs.netlify.com/site-deploys/overview/#deploy-contexts
  [plugins.inputs]
    contexts = [
      'production',
      'branch-deploy',
      'deploy-preview'
    ]
  # Optionally, override the default options for the minification
  # https://github.com/kangax/html-minifier#options-quick-reference
  [plugins.inputs.minifierOptions]
    removeComments = true
    collapseInlineTagWhitespace = true

    [[plugins]]
  package = "netlify-plugin-js-obfuscator"
  # All inputs are optional, so you can omit this section.
  # Defaults are shown below.
  # You can also refer to `javascript-obfuscator`’s documentation: https://github.com/javascript-obfuscator/javascript-obfuscator.
  [plugins.inputs]
   # Compact code output on one line.
     compact = false
   # Enables numbers conversion to expressions
     numbersToExpressions = true
   # Enables additional code obfuscation through simplification.
     simplify = true
   # Randomly shuffles the stringArray array items
     shuffleStringArray = true
   # Splits literal strings into chunks with length of splitStringsChunkLength option value
     splitStrings = true
